# Generated by Django 2.2.4 on 2020-02-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Votes',
            field=models.ManyToManyField(related_name='Votes', to='BlogApp.User'),
        ),
    ]
