# Generated by Django 2.2.4 on 2020-02-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_post_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=40),
        ),
    ]
